# Generated by Django 4.2.2 on 2024-06-03 18:11

import comum.utils
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Carro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50, verbose_name='Modelo')),
                ('ano', models.SmallIntegerField(verbose_name='Ano')),
                ('combustivel', models.CharField(max_length=50, verbose_name='Combustível')),
                ('marca', models.CharField(max_length=50, verbose_name='Marca')),
                ('valorBase', models.DecimalField(decimal_places=2, max_digits=9, verbose_name='Valor Base')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criacao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualizacao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo/Inativo')),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=255, verbose_name='Rua')),
                ('numero', models.CharField(max_length=255, verbose_name='Numero')),
                ('complemento', models.CharField(blank=True, default='', max_length=255, verbose_name='Complemento')),
                ('Bairro', models.CharField(max_length=255, verbose_name='Bairro')),
                ('cidade', models.CharField(max_length=255, verbose_name='Cidade')),
                ('estado', models.CharField(max_length=255, verbose_name='estado')),
                ('cep', models.CharField(max_length=255, verbose_name='CEP')),
                ('latitude', models.FloatField(verbose_name='latitude')),
                ('longitude', models.FloatField(verbose_name='longitude')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Data de criacao')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Data de atualizacao')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo/Inativo')),
            ],
        ),
        migrations.CreateModel(
            name='Recurso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50, verbose_name='Nome')),
                ('preco', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Preco')),
                ('carro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='site_concessionaria.carro', verbose_name='Carro_id')),
            ],
        ),
        migrations.CreateModel(
            name='Anexo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descricao')),
                ('arquivo', models.FileField(upload_to='site_concessionaria/', validators=[django.core.validators.FileExtensionValidator(['pdf', 'docx', 'xlsx', 'png', 'jpeg']), comum.utils.validate_file_size], verbose_name='Arquivo')),
                ('carro', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='site_concessionaria.carro', verbose_name='Carro')),
            ],
        ),
    ]
