# Generated by Django 4.2.2 on 2024-06-04 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('site_concessionaria', '0002_cliente_remove_carro_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agendamentos',
            options={'verbose_name': 'Agendamentos', 'verbose_name_plural': 'Agendamentos'},
        ),
    ]
