# Generated by Django 4.2.2 on 2024-06-05 18:36

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('site_concessionaria', '0003_alter_agendamentos_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='agendamentos',
            name='carro',
        ),
        migrations.RemoveField(
            model_name='agendamentos',
            name='cliente',
        ),
        migrations.RemoveField(
            model_name='agendamentos',
            name='loja',
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='contato',
            field=models.CharField(default='', max_length=100, verbose_name='Contato'),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='info_adicional',
            field=models.TextField(default='', max_length=1000),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='nome',
            field=models.CharField(default='', max_length=100, verbose_name='Nome Completo'),
        ),
        migrations.AddField(
            model_name='agendamentos',
            name='servico',
            field=models.CharField(choices=[('TestDrive', 'Test-drive'), ('TrocaOleo', 'Troca de Óleo')], default='TestDrive', verbose_name='Serviço'),
        ),
        migrations.AlterField(
            model_name='agendamentos',
            name='dataHoraAgendamento',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Data Hora Agendamento'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='created_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Data de Criacao'),
        ),
        migrations.AlterField(
            model_name='simulacao',
            name='updated_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Data de Atualização'),
        ),
    ]
